### DISCUSSION TITLE
How to detect changes in plan step

### DISCUSSION THREAD

**Discussion by palakraina** [devsectop/tf-via-pr#405] [Q&A] [answered]
Hi team, 
My plan step looks like this
```
- name: Terraform Plan with comment
        id: plan
        uses: OP5dev/tf-via-pr@v13
        with:
          working-directory: "./xyz"
          command: plan                     
          validate: true                    
          format: false
          comment-pr: always                    
          arg-detailed-exitcode: true
          show-args: true
```
          
       In my apply step, I want to run only if I detect any changes in plan step. How to get it correctly?
       Context: I want to keep my apply step separate and only run if `plan` step has detected changes. I tried using exit code but the step always gives exitcode 0.

**Comment by rdhar** [comment, marked as answer]
This is likely because of "hashicorp/setup-terraform" being used without `terraform_wrapper: false`, as documented in [their repo's open issue](https://github.com/hashicorp/setup-terraform/issues/328). Here's how to work around it to meet your given requirements:

```yaml
- name: Checkout repo
  uses: actions/checkout@v4

- name: Setup Terraform
  uses: hashicorp/setup-terraform@v3
  with:
    terraform_wrapper: false

- name: Terraform Plan
  id: plan
  uses: op5dev/tf-via-pr@v13
  with:
    working-directory: "./xyz"
    command: plan
    arg-lock: false
    validate: true

- name: Terraform Apply
  uses: op5dev/tf-via-pr@v13
  if: steps.plan.outputs.exitcode == 2
  with:
    working-directory: "./xyz"
    command: apply
    arg-lock: true
```

You don't need to give the following inputs, as they are set automatically to sensible defaults:
- `comment-pr`
- `arg-detailed-exitcode`
- `show-args`
- `format`

---

There are plenty more workflow examples you can pick-and-mix from.


<table>
  <tr>
    <td>
      <h4><a href="/.github/examples/pr_push_auth.yaml">#1 example ⤴</a></h4>
      <p>Runs on <code>pull_request</code> (plan) and <code>push</code> (apply) events with Terraform, AWS <strong>authentication</strong> and <strong>cache</strong>.</p>
      </br>
    </td>
    <td>
      <h4><a href="/.github/examples/pr_merge_matrix.yaml">#2 example ⤴</a></h4>
      <p>Runs on <code>pull_request</code> (plan) and <code>merge_group</code> (apply) events with OpenTofu in <strong>matrix</strong> strategy.</p>
      </br>
    </td>
  </tr>
  <tr>
    <td>
      <h4><a href="/.github/examples/pr_push_lint.yaml">#3 example ⤴</a></h4>
      <p>Runs on <code>pull_request</code> (plan) and <code>push</code> (apply) events with <strong>fmt/validate checks</strong> and TFLint.</p>
      </br>
    </td>
    <td>
      <h4><a href="/.github/examples/pr_push_stages.yaml">#4 example ⤴</a></h4>
      <p>Runs on <code>pull_request</code> (plan) and <code>push</code> (apply) events with <strong>conditional jobs</strong> based on plan file.</p>
      </br>
    </td>
  </tr>
  <tr>
    <td>
      <h4><a href="/.github/examples/pr_manual_label.yaml">#5 example ⤴</a></h4>
      <p>Runs on <code>labeled</code> and <code>workflow_dispatch</code> <strong>manual</strong> events on GitHub Enterprise (GHE) <strong>self-hosted runner</strong>.</p>
      </br>
    </td>
    <td>
      <h4><a href="/.github/examples/schedule_refresh.yaml">#6 example ⤴</a></h4>
      <p>Runs on <code>schedule</code> <strong>cron</strong> event with <code>-refresh-only</code> to open an issue on <strong>configuration drift</strong>.</p>
      </br>
    </td>
  </tr>
</table>
