### ISSUE TITLE
Query about destroy

### ISSUE THREAD

**Issue by chris3ware** [DevSecTop/TF-via-PR#306]
#### Describe the bug

When destroy is set to `true` the workflow fails with the following error:

> Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'id')

The command output shows that `init` is being run:

> /home/runner/work/_temp/6dbcc05e-3d4c-40b6-8209-249917242161/tofu -chdir=tf/dev/vpc init -lock=true

#### To Reproduce

Configure the action with the following arguments:

```
- name: Clean up resources
  if: github.event_name == 'push'
  uses: devsectop/tf-via-pr@86ff2b5756fb1c483c7c3ecc86f7c320c97a7302 # v11.4.1
  with:
    arg_chdir: tf-dir
    arg_command: apply
    arg_destroy: true
    arg_lock: true
    arg_auto_approve: true
```

Run the action, and view the command output:

> init -chdir=tfdir -destroy=true -lock=true

#### Expected behavior

The command being run should be: `-chdir=tfdir apply -destroy

#### Screenshots

Job Summary:

<img width="1021" alt="Screenshot 2024-09-19 at 11 18 10" src="https://github.com/user-attachments/assets/068fc9f8-8c34-406f-b3ea-b32ca9d4c6ea">

Workflow logs:

<img width="847" alt="Screenshot 2024-09-19 at 11 19 03" src="https://github.com/user-attachments/assets/5ebc0577-890a-4aa1-8fa0-73f2d05d4ebc">
