### ISSUE TITLE
tenv failing to install

### ISSUE THREAD

**Issue by ego93** [DevSecTop/TF-via-PR#308]
#### Describe the bug
I am running `v11.4.3` and running into an issue with the install step of `tenv` `v3.2.2`

```
 dpkg-deb: error: 'tenv_v3.2.2_amd64.deb' is not a Debian format archive
dpkg: error processing archive tenv_v3.2.2_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 tenv_v3.2.2_amd64.deb
```

I've also noticed that the install command of tenv is hardcoded to use `amd64`, which means it will not work for arm or other types or system architecture.
https://github.com/DevSecTop/TF-via-PR/blob/6cb2fdac68782ce1483824fa8db03b6accd77161/action.yml#L289
https://github.com/DevSecTop/TF-via-PR/blob/6cb2fdac68782ce1483824fa8db03b6accd77161/action.yml#L290

#### To Reproduce

```
      - name: Provision TF
        uses: devsectop/tf-via-pr@v11
        with:
          tenv_version: v3.2.2
```

#### Expected behavior

I would expect tenv to install without error
