### ISSUE TITLE
Running with matrix gives an error with jq.

### ISSUE THREAD

**Issue by silnels-greenlane** [DevSecTop/TF-via-PR#355]
#### Describe the bug

when running the action with a matrix if gives and error, i.e, `jq: error (at <stdin>:1): Unexpected extra JSON values (while parsing '32664615728`

using v12.0.5

#### To Reproduce

```
on:
  pull_request:
    branches:
      - "main"


jobs:
    prepare:
      outputs:
        environments: ${{ steps.filter.outputs.changes }}
      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
        - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
          id: filter
          with:
            filters: .github/file-filters.yaml
  ...
terraform-plan:
...
  strategy:
        matrix:
          environment: ${{ fromJSON(needs.prepare.outputs.environments) }}
  ...
      - uses: devsectop/tf-via-pr@a917bd222a6a780f25d2c5cd1942f6b2c2f16a7a # v12
        with:
          command: 'plan'
          working-directory: environments/${{ matrix.environment }}/terraform
```
