### ISSUE TITLE
Terraform validate var-file arg

### ISSUE THREAD

**Issue by joe-dematteo** [DevSecTop/TF-via-PR#359]
#### Describe the bug

The `terraform validate` command is being passed the `var-file` arg.

#### To Reproduce

```yml
  - name: Terraform Action
    id: terraform-action
    uses: devsectop/tf-via-pr@v12.0.7
    with:
      command: "plan"
      plan-encrypt: ${{ secrets.PLAN_PASSPHRASE }}
      format: true
      validate: true
      comment-pr: recreate
      arg-var-file: "terraform.tfvars"
```

#### Expected behavior

The `terraform validate` command does not get passed the `-var-file` arg.

#### Additional context

Is the arg file supposed to be being passed to the Terraform validate command?
